// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElAside: typeof import("element-plus/es")["ElAside"];
  const ElButton: typeof import("element-plus/es")["ElButton"];
  const ElContainer: typeof import("element-plus/es")["ElContainer"];
  const ElIcon: typeof import("element-plus/es")["ElIcon"];
  const ElMain: typeof import("element-plus/es")["ElMain"];
  const ElMenu: typeof import("element-plus/es")["ElMenu"];
  const ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
}
export {};
