// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElAlert: typeof import("element-plus/es")["ElAlert"];
  const ElAside: typeof import("element-plus/es")["ElAside"];
  const ElButton: typeof import("element-plus/es")["ElButton"];
  const ElCard: typeof import("element-plus/es")["ElCard"];
  const ElContainer: typeof import("element-plus/es")["ElContainer"];
  const ElIcon: typeof import("element-plus/es")["ElIcon"];
  const ElMain: typeof import("element-plus/es")["ElMain"];
  const ElMenu: typeof import("element-plus/es")["ElMenu"];
  const ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
  const ElMessage: typeof import("element-plus/es")["ElMessage"];
  const ElSubMenu: typeof import("element-plus/es")["ElSubMenu"];
}
export {};
