// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElAlert: typeof import('element-plus/es')['ElAlert'];
  const ElButton: typeof import('element-plus/es')['ElButton'];
  const ElCard: typeof import('element-plus/es')['ElCard'];
  const ElCollapse: typeof import('element-plus/es')['ElCollapse'];
  const ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem'];
  const ElIcon: typeof import('element-plus/es')['ElIcon'];
  const ElMenu: typeof import('element-plus/es')['ElMenu'];
  const ElMenuItem: typeof import('element-plus/es')['ElMenuItem'];
  const ElRadioButton: typeof import('element-plus/es')['ElRadioButton'];
  const ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup'];
  const ElSubMenu: typeof import('element-plus/es')['ElSubMenu'];
  const ElTag: typeof import('element-plus/es')['ElTag'];
}
export {};
