// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    AsideMenu: typeof import("./src/components/AsideMenu.vue")["default"];
    ElAside: typeof import("element-plus/es")["ElAside"];
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElContainer: typeof import("element-plus/es")["ElContainer"];
    ElIcon: typeof import("element-plus/es")["ElIcon"];
    ElMain: typeof import("element-plus/es")["ElMain"];
    ElMenu: typeof import("element-plus/es")["ElMenu"];
    ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
    HelloWorld: typeof import("./src/components/HelloWorld.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
  }
}

export {};
