// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AsideMenu: typeof import('./src/components/AsideMenu.vue')['default'];
    Author: typeof import('./src/components/global/Author.vue')['default'];
    ElAlert: typeof import('element-plus/es')['ElAlert'];
    ElButton: typeof import('element-plus/es')['ElButton'];
    ElCard: typeof import('element-plus/es')['ElCard'];
    ElCollapse: typeof import('element-plus/es')['ElCollapse'];
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem'];
    ElIcon: typeof import('element-plus/es')['ElIcon'];
    ElMenu: typeof import('element-plus/es')['ElMenu'];
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem'];
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton'];
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup'];
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu'];
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
  }
}

export {};
